### ISSUE TITLE
ll-builder download URL does not follow redirect

### ISSUE THREAD

**Issue by abcfy2** [linuxdeepin/developer-center#5492]
### SUMMARY | 问题概要

Sample linglong.yaml:

```yaml
package:
  id: boost
  name: boost
  version: 1.83.0
  kind: lib
  description: |
    Boost provides free peer-reviewed portable C++ source libraries.

runtime:
  id: org.deepin.Runtime
  version: 20.5.0

source:
  kind: archive
  url: "https://sourceforge.net/projects/boost/files/boost/1.83.0/boost_1_83_0.tar.bz2"

build:
  kind: manual
  manual:
    configure: |
      if [ ! -f ./b2 ]; then
        ./bootstrap.sh
      fi
      cd "tools/build"
      if [ ! -f ./b2 ]; then
        ./bootstrap.sh
      fi
    install: |
      ./b2 -d0 -q install --with-system variant=release link=shared runtime-link=shared
      cd "tools/build"
      ./b2 -d0 -q install variant=release link=shared runtime-link=shared
```

```sh
❯ ll-builder build
Searching ll-builder config in: ("/home/fengyu/projects/linglong-packages/boost/.ll-builder/config.yaml", "/home/fengyu/projects/linglong-packages/.ll-builder/config.yaml", "/home/fengyu/projects/.ll-builder/config.yaml", "/home/fengyu/.ll-builder/config.yaml", "/home/.ll-builder/config.yaml", "//.ll-builder/config.yaml", "/home/fengyu/.local/share/linglong/builder/config.yaml", "/usr/local/share/linglong/builder/config.yaml", "/usr/share/linglong/builder/config.yaml", "/usr/local/etc/linglong/builder/config.yaml", "/usr/local/share/linglong/builder/config.yaml")
load config from "/usr/local/share/linglong/builder/config.yaml"
looking repo at: "/home/fengyu/.cache/linglong-builder/repo"
ostree repo path is "/home/fengyu/.cache/linglong-builder/repo"
start "-v --repo=/home/fengyu/.cache/linglong-builder/repo remote show-url repo"
"https://mirror-repo-linglong.deepin.com/repos/repo\n"
QProcess::NormalExit with exit code: 0
QIODevice::read (QFile, ":/strip.sh"): device not open
"building target: boost"
"fetching source code from: https://sourceforge.net/projects/boost/files/boost/1.83.0/boost_1_83_0.tar.bz2"
QVariant(qlonglong, 176)
"mismatched hash: 5915768f633e23a4744700b05247ca5cf96484191a88a8c188d965d25e993d5c"
Error (code=-1) occurs in function 
MISSING function name 
at MISSING file name:0 
message: fetch source failed
~OstreeRepoHelper() called
```

This because `https://sourceforge.net/projects/boost/files/boost/1.83.0/boost_1_83_0.tar.bz2` will redirect to the final download URL.

`wget` will work:

```sh
❯ LC_ALL=C.UTF-8 wget https://sourceforge.net/projects/boost/files/boost/1.83.0/boost_1_83_0.tar.bz2
--2023-09-06 23:43:07--  https://sourceforge.net/projects/boost/files/boost/1.83.0/boost_1_83_0.tar.bz2
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving sourceforge.net (sourceforge.net)... 2606:4700:4400::6812:256f, 2606:4700:4400::ac40:9691, 104.18.37.111, ...
Connecting to sourceforge.net (sourceforge.net)|2606:4700:4400::6812:256f|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sourceforge.net/projects/boost/files/boost/1.83.0/boost_1_83_0.tar.bz2/ [following]
--2023-09-06 23:43:09--  https://sourceforge.net/projects/boost/files/boost/1.83.0/boost_1_83_0.tar.bz2/
Reusing existing connection to [sourceforge.net]:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sourceforge.net/projects/boost/files/boost/1.83.0/boost_1_83_0.tar.bz2/download [following]
--2023-09-06 23:43:09--  https://sourceforge.net/projects/boost/files/boost/1.83.0/boost_1_83_0.tar.bz2/download
Reusing existing connection to [sourceforge.net]:443.
HTTP request sent, awaiting response... 302 Found
Location: https://downloads.sourceforge.net/project/boost/boost/1.83.0/boost_1_83_0.tar.bz2?ts=gAAAAABk-J4NxZG21FEdNI1LkqMOuRb3vhYjfCmg2H4wJj-MA09YXtR5kqYU1B5st5SpbMgGTc5VAyvUCkAuehrYEcjipPD3gA%3D%3D&use_mirror=newcontinuum&r= [following]
--2023-09-06 23:43:09--  https://downloads.sourceforge.net/project/boost/boost/1.83.0/boost_1_83_0.tar.bz2?ts=gAAAAABk-J4NxZG21FEdNI1LkqMOuRb3vhYjfCmg2H4wJj-MA09YXtR5kqYU1B5st5SpbMgGTc5VAyvUCkAuehrYEcjipPD3gA%3D%3D&use_mirror=newcontinuum&r=
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 204.68.111.105
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|204.68.111.105|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://newcontinuum.dl.sourceforge.net/project/boost/boost/1.83.0/boost_1_83_0.tar.bz2 [following]
--2023-09-06 23:43:11--  https://newcontinuum.dl.sourceforge.net/project/boost/boost/1.83.0/boost_1_83_0.tar.bz2
Resolving newcontinuum.dl.sourceforge.net (newcontinuum.dl.sourceforge.net)... 2607:ff50:0:11::32, 64.79.96.4
Connecting to newcontinuum.dl.sourceforge.net (newcontinuum.dl.sourceforge.net)|2607:ff50:0:11::32|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 122892751 (117M) [application/octet-stream]
Saving to: ‘boost_1_83_0.tar.bz2’

boost_1_83_0.tar.bz2                                2%[=>                                                                                                            ]   2.77M   604KB/s    eta 3m 7s
```

but ll-builder does not follow this redirect.

```sh
❯ cat .linglong-target/boost/fetch/cache/boost_1_83_0.tar.bz2
301 Moved Permanently

The resource has been moved to https://sourceforge.net/projects/boost/files/boost/1.83.0/boost_1_83_0.tar.bz2/; you should be redirected automatically. 
```

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
archlinux
```

### STEPS TO REPRODUCE | 复现步骤

AS above.
